// This function sends an email using SMTP.js when called
function sendEmail() {
    var parentName = document.getElementById("gname").value;
    var parentEmail = document.getElementById("gmail").value;
    var childName = document.getElementById("cname").value;
    var childAge = document.getElementById("cage").value;
    var message = document.getElementById("message").value;

    var emailBody = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>New Inquiry - Professional Layout</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body style="background-color: #f4f6f9; padding-top: 20px; padding-bottom: 20px;">
        <div class="container">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white text-center">
                    <h4>New Inquiry Submission</h4>
                </div>
                <div class="card-body">
                    <h5 class="mb-3">You have received a new inquiry:</h5>
                    
                    <table class="table table-bordered">
                        <tr>
                            <th>Parent Name</th>
                            <td>${parentName}</td>
                        </tr>
                        <tr>
                            <th>Parent Email</th>
                            <td>${parentEmail}</td>
                        </tr>
                        <tr>
                            <th>Child Name</th>
                            <td>${childName}</td>
                        </tr>
                        <tr>
                            <th>Child Age</th>
                            <td>${childAge}</td>
                        </tr>
                        <tr>
                            <th>Message</th>
                            <td>${message}</td>
                        </tr>
                    </table>

                    <div class="alert alert-info" role="alert">
                        This is an automated message generated by the inquiry form.
                    </div>
                </div>
                <div class="card-footer text-muted text-center">
                    <p>Thank you for your attention!</p>
                </div>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>
    `;

    // Send email to the fixed email address
    Email.send({
        Host: "smtp.gmail.com",
        Username: "pinalcuriouslearners@gmail.com",  // Your Gmail address
        Password: "bhae clku wstx xdqb",    // Your Gmail App Password
        To: 'rahul.patel17899@gmail.com', // Fixed recipient email address
        From: "pinalcuriouslearners@gmail.com",     // Your Gmail address
        Subject: "New Inquiry from " + parentName,
        Body: emailBody, // Send the HTML-formatted email body
        IsHTML: true // Indicate that the body is HTML
    })
    .then(function (message) {
        alert("Mail sent successfully!");
        // Hide the form and show the thank you message
        document.getElementById("inquiry-form").style.display = "none";
        document.getElementById("thank-you-message").style.display = "block";
    })
    .catch(function (error) {
        alert("Failed to send mail: " + error.message);
    });
}
